<?php

return [
    'NAV'=>[
        [
            'name'=>'管理员',
            'icon'=>'user',
            'access'=>[
                [
                'name'=>'管理员列表',
                'access'=>'admin/admin/index',
                'icon'=>''
                ],
                [
                'name'=>'角色列表',
                'access'=>'admin/role/index',
                'icon'=>''
                ],
                [
                    'name'=>'管理员列表',
                    'access'=>'admin/admin/index',
                    'icon'=>''
                ],
                [
                    'name'=>'管理员列表',
                    'access'=>'admin/admin/index',
                    'icon'=>''
                ],
            ]
        ],[
            'name'=>'管理员',
            'icon'=>'user',
            'access'=>[
                [
                'name'=>'管理员列表',
                'access'=>'admin/admin/index',
                'icon'=>''
                ],
                [
                'name'=>'角色列表',
                'access'=>'admin/role/index',
                'icon'=>''
                ],
                [
                    'name'=>'管理员列表',
                    'access'=>'admin/admin/index',
                    'icon'=>''
                ],
                [
                    'name'=>'管理员列表',
                    'access'=>'admin/admin/index',
                    'icon'=>''
                ],
            ]
        ],
    ],

];
